# Generated by Django 2.2.2 on 2019-08-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_categoria_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_nascimento_user',
            field=models.DateField(blank=True, null=True),
        ),
    ]
