# Generated by Django 2.2.2 on 2019-11-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_informacoes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avaliacao',
            field=models.FloatField(null=True),
        ),
    ]
