# Generated by Django 2.2.2 on 2019-08-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190819_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_categoria',
            name='categoria_categoria',
            field=models.CharField(max_length=30),
        ),
    ]
