# Generated by Django 2.2.2 on 2019-08-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190823_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='categoria_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Usuario_Categoria'),
        ),
    ]
