# Generated by Django 2.2.4 on 2019-12-04 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191204_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoes',
            name='user_comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='imagem',
            field=models.ImageField(blank=True, default='perfil_default.jpeg', null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='informacoes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
