# Generated by Django 2.2.2 on 2019-08-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190825_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='categoria',
            field=models.CharField(choices=[(1, 'Prestador'), (2, 'Consumidor')], max_length=20, null=True),
        ),
    ]
