# Generated by Django 2.2.2 on 2019-08-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='categoria',
            field=models.CharField(choices=[('Prestador', 'Prestador'), ('Consumidor', 'Consumidor')], max_length=20, null=True),
        ),
    ]
