# Generated by Django 2.2.4 on 2019-12-04 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191204_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
