# Generated by Django 2.2.2 on 2019-09-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190825_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_categoria',
            name='categoria_categoria',
        ),
        migrations.AddField(
            model_name='customuser',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_nasc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='descricao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='endereço',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='estado',
            field=models.CharField(blank=True, choices=[('PARANÁ', 'PR'), ('RIO GRANDE DO SUL', 'RS'), ('São Paulo', 'SP'), ('Santa Catarina', 'SC')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'MASCULINO'), ('Feminino', 'Fem')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
