# Generated by Django 2.2.4 on 2019-12-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avaliacao',
            field=models.FloatField(default=0.0),
        ),
    ]
