# Generated by Django 2.2.2 on 2019-09-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190901_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos_Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_servico', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Servicos_Categoria'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='../media'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MAS', 'Masculino'), ('FEM', 'Feminino')], max_length=11, null=True),
        ),
    ]
