# Generated by Django 2.2.2 on 2019-09-02 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190902_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='categoria_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Servicos_Categoria'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='categoria',
            field=models.CharField(choices=[('Prestador', 'Prestador'), ('Consumidor', 'Consumidor')], max_length=20, null=True),
        ),
    ]
