# Generated by Django 2.2.2 on 2019-09-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190902_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imagem',
            field=models.ImageField(blank=True, default='https://miro.medium.com/max/3200/1*g09N-jl7JtVjVZGcd-vL2g.jpeg', null=True, upload_to='../media'),
        ),
    ]
