# Generated by Django 2.2.2 on 2019-11-04 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Servicos_Categoria')),
                ('user_demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Propostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposta', models.TextField()),
                ('valor', models.FloatField(blank=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Demandas')),
                ('to_user_proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_proposta', to=settings.AUTH_USER_MODEL)),
                ('user_proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_proposta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_servico', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Ativo', max_length=240)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('cancel_confirm', models.BooleanField(default=False)),
                ('avaliacao', models.FloatField(blank=True, default=0)),
                ('sugestao_critica', models.TextField(blank=True, default='')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Propostas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_prestador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_prestador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_usuario', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='para_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.MessageSession')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Interesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('interesse', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Demandas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('user_interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interesse', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_comentario', to=settings.AUTH_USER_MODEL)),
                ('user_prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_prestador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
