# Generated by Django 2.2.2 on 2019-08-18 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_servico', models.CharField(max_length=50)),
                ('descricao_servico', models.CharField(max_length=250)),
                ('data_servico', models.DateTimeField(default=django.utils.timezone.now)),
                ('requisitos_servico', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_ofertas', models.CharField(max_length=50)),
                ('descricao_ofertas', models.CharField(max_length=250)),
                ('data_oferta', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagem_oferta', models.CharField(max_length=250)),
                ('usuario_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_oferta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesse', models.CharField(max_length=100)),
                ('data_interesse', models.DateTimeField(default=django.utils.timezone.now)),
                ('interesse_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='INTERESSE_SERVICO', to='principal.Servicos')),
                ('usuario_interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_interesse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_interesse'],
            },
        ),
        migrations.CreateModel(
            name='Demandas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_demanda', models.CharField(max_length=50)),
                ('descricao_demanda', models.CharField(max_length=250)),
                ('data_demanda', models.DateTimeField(default=django.utils.timezone.now)),
                ('requisitos_demanda', models.CharField(max_length=150)),
                ('anexo_demanda', models.CharField(max_length=250)),
                ('imagem_demanda', models.CharField(max_length=250)),
                ('avaliacao_demanda', models.CharField(max_length=10)),
                ('status_demanda', models.CharField(choices=[('E', 'ESPERA'), ('', ''), ('', '')], default='ESPERA', max_length=20)),
                ('usuario_demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_servicos', to=settings.AUTH_USER_MODEL)),
                ('usuario_prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios_Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=100)),
                ('data_comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_comentario', to=settings.AUTH_USER_MODEL)),
                ('usuario_prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_prestador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hora_comentario'],
            },
        ),
    ]
