# Generated by Django 2.2.2 on 2019-08-19 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='imagem_demanda',
            field=models.ImageField(max_length=250, upload_to=''),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='usuario_prestador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
