# Generated by Django 2.2.2 on 2019-11-04 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='user_prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prestador', to=settings.AUTH_USER_MODEL),
        ),
    ]
