# Generated by Django 2.2.2 on 2019-10-07 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesses',
            name='interesse_servico',
        ),
        migrations.AddField(
            model_name='interesses',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interesses',
            name='interesse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Demandas'),
        ),
    ]
