# Generated by Django 2.2.2 on 2019-10-13 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20191007_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesses',
            name='interesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Demandas'),
        ),
        migrations.AlterField(
            model_name='interesses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interesses',
            name='usuario_interesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_interesse', to=settings.AUTH_USER_MODEL),
        ),
    ]
