# Generated by Django 2.2.2 on 2019-08-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20190819_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
