# Generated by Django 2.2.2 on 2019-11-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_message_is_proposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostas',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
