# Generated by Django 2.2.2 on 2019-11-28 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_propostas_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='proposta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Propostas'),
        ),
    ]
