# Generated by Django 2.2.2 on 2019-08-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20190820_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='anexo_demanda',
            field=models.FileField(max_length=250, null=True, upload_to='../media'),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='imagem_demanda',
            field=models.ImageField(max_length=250, null=True, upload_to='../anexos'),
        ),
    ]
