# Generated by Django 2.2.2 on 2019-11-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_message_proposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='status',
            field=models.CharField(default='Ativo', max_length=30),
        ),
    ]
