# Generated by Django 2.2.2 on 2019-08-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20190821_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='imagem_demanda',
            field=models.ImageField(max_length=250, null=True, upload_to='../media'),
        ),
    ]
