# Generated by Django 2.2.2 on 2019-10-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_servicos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostas',
            name='demanda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Demandas'),
        ),
    ]
