# Generated by Django 2.2.2 on 2019-09-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20190825_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='imagem_oferta',
            field=models.ImageField(null=True, upload_to='../media'),
        ),
    ]
