# Generated by Django 2.2.4 on 2019-12-04 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_demandas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostas',
            name='aceito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='proposta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='principal.Propostas'),
        ),
        migrations.AlterField(
            model_name='propostas',
            name='demanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.Demandas'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='proposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.Propostas'),
        ),
        migrations.DeleteModel(
            name='Interesses',
        ),
    ]
