# Generated by Django 2.2.2 on 2019-10-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_propostas_demanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='avaliacao',
            field=models.FloatField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicos',
            name='cancel_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicos',
            name='justificativa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicos',
            name='sugestao_critica',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='interesses',
            name='interesse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Demandas'),
        ),
    ]
