# Generated by Django 2.2.2 on 2019-09-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20190901_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Servicos_Categoria'),
        ),
        migrations.DeleteModel(
            name='Servicos_Categoria',
        ),
    ]
