# Generated by Django 2.2.4 on 2019-12-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20191204_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='avaliacao_do_prestador',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
