# Generated by Django 2.2.4 on 2019-12-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_servicos_avaliacao_do_prestador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
    ]
